# models/schema.yml

version: 2

models:
  - name: all_vehicles
    description: |
      This dbt view returns all columns and rows from the "vehicle_data" table.

    columns:
      - name: track_id
        description: The unique identifier for each vehicle's track.

      - name: type
        description: The type of the vehicle.

      - name: traveled_d
        description: The distance traveled by the vehicle.

      - name: avg_speed
        description: The average speed of the vehicle.

  - name: avg_dist_by_type
    description: |
      This dbt view calculates the average traveled distance by vehicle type in the "vehicle_data" table.

    columns:
      - name: Vehicle Type
        description: The type of vehicle.

      - name: Average Distance
        description: Average traveled distance for each vehicle type.

  - name: avg_distance_speed
    description: |
      This dbt view combines data from 'avg_dist_by_type', 'avg_speed_by_type', and 'count_by_type'
      to provide the average distance, average speed, and type count for each vehicle type.

    columns:
      - name: Average Distance
        description: Average traveled distance for each vehicle type.

      - name: Average Speed
        description: Average speed for each vehicle type.

      - name: Vehicle Type
        description: The type of vehicle.

      - name: Type Count
        description: Count of rows for each vehicle type.

  - name: avg_speed_by_type
    description: |
      This dbt view calculates the average speed by vehicle type in the "vehicle_data" table.

    columns:
      - name: Vehicle Type
        description: The type of vehicle.

      - name: Average Speed
        description: Average speed for each vehicle type.

  - name: count_by_type
    description: |
      This dbt view calculates the count of rows for each vehicle type in the "vehicle_data" table.

    columns:
      - name: Vehicle Type
        description: The type of vehicle.

      - name: Type Count
        description: Count of rows for each vehicle type.

  - name: distance_distribution
    description: |
      This dbt view calculates the distribution of traveled distances in the "vehicle_data" table.

    columns:
      - name: Traveled Distance
        description: The distance traveled by vehicles.

      - name: Vehicle Count
        description: Count of vehicles for each traveled distance.

  - name: vehicle_summary
    description: |
      This dbt view provides a summary of information about automobiles from the "vehicle_data" table.

    columns:
      - name: Automobile type
        description: The type of automobile.

      - name: Automobile count
        description: Count of automobiles for each type.

      - name: Avg distance traveled
        description: Average distance traveled for each type of automobile.

      - name: Avg speed by automobile
        description: Average speed for each type of automobile.
