# ~/.dbt/profiles.yml

my_project:
  target: dev
  outputs:
    dev:
      type: postgres
      host: postgres # Replace with your PostgreSQL host
      user: airflow # Replace with your PostgreSQL username
      password: airflow # Replace with your PostgreSQL password
      port: 5432 # Replace with your PostgreSQL port
      dbname: airflow # Replace with your PostgreSQL database name
      schema: public # Replace with the schema you want to use for dbt
      threads: 4
      timeout_seconds: 300
